[package]
name        = "macaroons"
description = "Cookie-like bearer credentials with caveats for distributed authorization"
homepage    = "https://github.com/cryptosphere/rust-macaroons"
repository  = "https://github.com/cryptosphere/rust-macaroons.git"
readme      = "README.md"
keywords    = ["cookies", "authorization", "credentials"]
license     = "MIT"
version     = "0.2.1"
authors     = ["Tony Arcieri <bascule@gmail.com>"]

[features]
nightly = []

[dependencies.sodiumoxide]

[dependencies.libsodium-sys]

[dependencies.rustc-serialize]
